### ISSUE TITLE
我的学习日志(十)

### ISSUE THREAD

**Issue by shimuash** [xxxgitone/learningProcess#12]
文字超出时显示省略号

一行文字省略号
```css
p {
  width: 200px;
  height: 36px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space:nowrap;
}
```
两行文字省略号

```css
width: 100%;
height: 2.3rem;
overflow: hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-line-clamp: 2;
-webkit-box-orient: vertical;
```
